# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: öryggi kappi
email: 0xiammyr at protonmail dot com
description: > # this means to ignore newlines until "baseurl:"
  Bits and pieces I come across while going through my (mainly security-related) projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iammyr.github.io" # the base hostname & protocol for your site
twitter_username: iammyr
github_username:  iammyr

# Build settings
markdown: kramdown

theme: jekyll-theme-hacker